export const inputsArray = [
  {
    id: 1,
    name: "name",
    type: "text",
    placeholder: "name",
    label: "Name",
    errorMessage: "Name is required",
    required: true,
  },
  {
    id: 2,
    name: "username",
    type: "text",
    placeholder: "username",
    label: "Username",
    errorMessage: "Username is required",
    required: true,
  },
  {
    id: 3,
    name: "email",
    type: "email",
    placeholder: "email",
    label: "Email",
    errorMessage: "Email is required",
    required: true,
  },
  {
    id: 4,
    address: {
      street: {
        id: 1,
        name: "street",
        type: "text",
        placeholder: "City",
        label: "City",
        errorMessage: "City is required",
        required: true,
      },
      suite: {
        id: 2,
        name: "suite",
        type: "text",
        placeholder: "Suite",
        label: "Suite",
        errorMessage: "Suite is required",
        required: true,
      },
      city: {
        id: 3,
        name: "city",
        type: "text",
        placeholder: "City",
        label: "City",
        errorMessage: "City is required",
        required: true,
      },
    },
  },
];
